version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: thc_master_nginx
    ports:
      - "8098:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0.22
    container_name: thc_master_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4320:3306"
    environment:
      MYSQL_DATABASE: dev_master
      MYSQL_USER: dev_master
      MYSQL_PASSWORD: Dev@077#
      MYSQL_ROOT_PASSWORD: Dev@077#
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thc_master_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9012:9000"
    networks:
      - laravel

  npm:
    image: node:14.15.4
    container_name: thc_master_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel

  # artisan:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: thc_master_artisan
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - mysql
  #   working_dir: /var/www/html
  #   entrypoint: ["/var/www/html/artisan"]
  #   networks:
  #     - laravel

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   container_name: thc_master_phpmyadmin
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8086:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: secret
  #   networks:
  #     - laravel
